### ISSUE TITLE
feat: Materi Part 1 Chapter 3 - Menata Teks dan Font

### ISSUE THREAD

**Issue by iniakunhuda** [surabayadev/tutorial-css-lengkap#5]
### Chapter 3: Menata Teks dan Font
- **Lesson 1: Pengaturan Font dan Warna**
  - Properti `color`, `font-size`, `font-family`
  - Penggunaan font web-safe dan custom font (Google Fonts)
- **Lesson 2: Spasi dan Perataan Teks**
  - Properti `line-height`, `letter-spacing`, `text-align`
  - Mengatur jarak antar huruf dan baris teks
- **Lesson 3: Dekorasi dan Transformasi Teks**
  - Properti `text-decoration`, `text-transform`
  - Efek underline, overline, capitalize, dll.

**Comment by yodanisesutantio** [comment]
Boleh di assign ke Materi ini mas @iniakunhuda terima kasih 😁

**Comment by iniakunhuda** [comment]
> Boleh di assign ke Materi ini mas @iniakunhuda terima kasih 😁

Done, ikutin guideline disini ya buat create branchnya 🙌🏻 #3
